Controllers/HomeController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_Instadev.Models;
using Microsoft.AspNetCore.Http;

namespace Project_Instadev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        User userModel = new User();
        [TempData]

        public string Mensagem { get; set; }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Logando(IFormCollection form)
        {
            // Lemos todos os arquivos do CSV
            List<string> csv = userModel.ReadAllLinesCSV("Database/register.csv");

            // Verificamos se as informações passadas existe na lista de string
            var logado =
             csv.Find(
            x =>
            x.Split(";")[1] == form["Email"] &&
            x.Split(";")[4] == form["Senha"]
             );


            // Redirecionamos o usuário logado caso encontrado
            if (logado != null)
            {
                HttpContext.Session.SetString("E-mail", logado.Split(";")[1]);
                HttpContext.Session.SetString("IdUser", logado.Split(";")[0]);
                return LocalRedirect("~/Feed");
            }

            Mensagem = "Dados incorretos, tente novamente...";
            return LocalRedirect("~/");

        }

        [Route("Logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("_UserName");
            return LocalRedirect("~/");
        }
    }
}

Controllers/PublicationController.cs
using Project_Instadev.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace Project_Instadev.Controllers
{
    [Route("Feed")]
    public class PublicationController : Controller
    {
        Publication pubModels = new Publication();

        public IActionResult Feed()
        {
            User user = new User();
            ViewBag.Publications = pubModels.ReadAllItens();
              
            return View();
        }

        [Route("Publicar")]
        public IActionResult Publicar(IFormCollection form)
        {
          
            Publication newPub = new Publication();
          
            newPub.IdPublication = pubModels.idGPublication();
            newPub.Subtitle = form["Subtitle"];
            newPub.Image = form["Image"];


            // Inicio uploud
            if (form.Files.Count > 0)
            {
                //Se sim,
                //Armazenamos o arquivo na variável file
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Posts");

                // Verificamos se a pasta Equipes não existe
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                //localhost:5001           +        + Equipes + equipe.jpg        
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    // Salvamos o arquivo no caminho especificado
                    file.CopyTo(stream);
                }
                newPub.Image = file.FileName;
            }


            // Uploud termino
            newPub.Subtitle = form["Subtitle"];
           


            // Chamamos o método Create para salvar
            // a novaEquipe no CSV
            pubModels.Create(newPub);
            
           
            return LocalRedirect("~/Feed");
        }

        [Route("Delete")]
        public IActionResult Delete(int id)
        {
            pubModels.Delete(id);
            ViewBag.Publications = pubModels.ReadAllItens();
            return LocalRedirect("~/Feed");
        }
    }
}

Controllers/UserController.cs
using System;
using Project_Instadev.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Project_Instadev.Controllers
{
    // localhost:5001/User
    [Route("Register")]
    public class UserController : Controller
    {
        User userModels = new User();

        // localhost:5001/User/Register
        public IActionResult Register()
        {
            ViewBag.Users = userModels.ReadAllItems();
            return View();
        }

        // localhost:5001/User/New
        [Route("New")]
        public IActionResult Registration(IFormCollection registrationForm)
        { // o IActionResult e o IFormCollection fazem parte de bibliotecas do AspNetCore
            User newUser = new User();
            newUser.Email = registrationForm["Email"];
            newUser.CompleteName = registrationForm["CompleteName"];
            newUser.UserName = registrationForm["UserName"];
            newUser.Password = registrationForm["Password"];
            newUser.Photo = "default.png";

            newUser.IdUser = userModels.IdGenerator(); // o IdUser do usuário será igual ao método IdGenerator dentro do userModels || assim, será gerado toda vez que o método de Register for executado 

            userModels.Create(newUser);
            ViewBag.Users = userModels.ReadAllItems();
            

            // localhost:5001/User/Register
            return LocalRedirect("~/");
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Login";
}
<main>

    <section id="conteudo">
        <div class="centraform">
            <form method="POST" action='@Url.Action("Logando")'>
                <div class="centralizarlogo">
                    <img src="/img/Instadev (1).svg" alt="Logotipo do site Instadev">
                </div>

                <input class="input" type="email" name="Email" placeholder="E-mail" required>
                <input class="input" type="password" name="Senha" placeholder="Senha" required>
                <a asp-area="direcionando para o feed" asp-controller="Publication" asp-action="Feed">
                    <input class="botao" type="submit" value=Entrar>
                </a><br>
                <div class="erro">@TempData.Peek("Mensagem")</div>


                <p class="esqueciasenha"><a href="#">Esqueceu a senha?</a></p>
                @* <hr class="hr2"> *@
                <div class="testehr">
                    <hr>
                    <p>OU</p>
                    <hr>
                </div>
            </form>

        </div>
    </section>
    <section class="centralizarcadastrese">
        <div class="centralizarlink">
            <p>Não tem uma conta? </p>
            <p><a asp-area="direcionamento para cadastro" asp-controller="User"
                    asp-action="Register" class="cad">&nbspCadastre-se</a></p>

        </div>
    </section>
    <p class="frasenocentro">Obtenha o aplicativo.</p>
    <div class="centrafoot">
        <div class="store">
            <a href="https://www.apple.com/pt/ios/app-store/">
                <img src="/img/app_store 1.jpg" alt="linkda AppStore">
            </a>
            <a href="https://play.google.com/store">
                <img src="/img/google_play 1.png" alt="Link do GooglePlay">
            </a>

        </div>

    </div>
</main>